name       : kicad-footprints
version    : 5.1.12
release    : 5
source     :
    - https://gitlab.com/kicad/libraries/kicad-footprints/-/archive/5.1.12/kicad-footprints-5.1.12.tar.bz2 : 2f32db7986bfd7c9d42420542d83733c27a604270697e90c9affa15a0cc4707a
license    : CC-BY-SA-4.0
component  : office.scientific
summary    : Official KiCad Footprint Libraries
description: |
    The libraries are intended to be used with KiCad.
setup      : |
    %cmake
install    : |
    %make_install
