name       : kicad-footprints
version    : 5.0.0
release    : 1
source     :
    - https://github.com/KiCad/kicad-footprints/archive/5.0.0.tar.gz : 26c0231043b66e75d02aa5e5c9b51a07966e3aed8c17df22c255aa379104e2a6
license    : CC-BY-SA-4.0
component  : office
summary    : Official KiCad Footprint Libraries
description: |
    The libraries are intended to be used with KiCad.
setup      : |
    %cmake
install    : |
    %make_install
