name       : kicad-footprints
version    : 5.1.2
release    : 3
source     :
    - https://github.com/KiCad/kicad-footprints/archive/5.1.2.tar.gz : fb0f983393c78dc9bb0b060827a98e57d96abe9881f9fb356c2afdecc0fdbfd1
license    : CC-BY-SA-4.0
component  : office
summary    : Official KiCad Footprint Libraries
description: |
    The libraries are intended to be used with KiCad.
replaces   :
    - kicad-library
setup      : |
    %cmake
install    : |
    %make_install
