name       : kicad-footprints
version    : 7.0.6
release    : 6
source     :
    - https://gitlab.com/kicad/libraries/kicad-footprints/-/archive/7.0.6/kicad-footprints-7.0.6.tar.gz : 577fad1792bcca998b369d62d8e576191c94c507e700d2ae55309fbe3bba9556
license    : CC-BY-SA-4.0
component  : office.scientific
summary    : Official KiCad Footprint Libraries
description: |
    The libraries are intended to be used with KiCad.
setup      : |
    %cmake
install    : |
    %make_install
